---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: helm-toolkit
data:
  chart_name: helm-toolkit
  release: helm-toolkit
  namespace: helm-toolkit
  timeout: 300
  values: {}
  source:
    type: tar
    location: https://v1k0d3n.github.io/demo/charts/newton/helm-toolkit-3.0.3.tgz
    subpath: helm-toolkit
    reference: null
  dependencies: []
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: prometheus
data:
  chart_name: prometheus
  release: prometheus
  namespace: openstack
  timeout: 300
  values:
    storage:
      alertmanager:
        storage_class: default
      prometheus:
        storage_class: default
  source:
    type: tar
    location: https://v1k0d3n.github.io/demo/charts/newton/prometheus-3.0.3.tgz
    subpath: prometheus
    reference: null
  dependencies:
    - helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: grafana
data:
  chart_name: grafana
  release: grafana
  namespace: openstack
  timeout: 300
  values: {}
  source:
    type: tar
    location: https://v1k0d3n.github.io/demo/charts/newton/grafana-3.0.3.tgz
    subpath: grafana
    reference: null
  dependencies:
    - helm-toolkit
---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: monitoring-components
data:
  description: "Monitoring Components"
  sequenced: False
  chart_group:
    - prometheus
    - grafana
---
schema: armada/Manifest/v1
metadata:
  schema: metadata/Document/v1
  name: armada-manifest
data:
  release_prefix: ctec
  chart_groups:
    - monitoring-components
