---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: helm-toolkit
data:
  chart_name: helm-toolkit
  release: helm-toolkit
  namespace: helm-toolkit
  timeout: 300
  values: {}
  source:
    type: git
    location: https://github.com/openstack/openstack-helm
    subpath: helm-toolkit
    reference: 5eb51cf118f9dd2a19def9b4bf4afeec2aa3d3d7
  dependencies: []
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: prometheus
data:
  chart_name: prometheus
  release: prometheus
  namespace: monitoring
  timeout: 300
  values: {}
  source:
    type: git
    location: https://github.com/larryrensing/openstack-helm
    subpath: prometheus
    reference: monitoring
  dependencies:
    - helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: grafana
data:
  chart_name: grafana
  release: grafana
  namespace: monitoring
  timeout: 300
  values: {}
  source:
    type: git
    location: https://github.com/larryrensing/openstack-helm
    subpath: grafana
    reference: monitoring-dash
  dependencies:
    - helm-toolkit
---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: monitoring-components
data:
  description: "Monitoring Components"
  sequenced: False
  chart_group:
    - prometheus
    - grafana
---
schema: armada/Manifest/v1
metadata:
  schema: metadata/Document/v1
  name: armada-manifest
data:
  release_prefix: ctec
  chart_groups:
    - monitoring-components
